### ISSUE TITLE
IP22 Charger - incorrect reading for "AC Current"

### ISSUE THREAD

**Issue by thomasjobs** [mp-se/victron-receiver#4]
I discovered an incorrect value sent by the IP22 Charger - AC Current (ac_current). In my installation it's reported as 510 (A), correct value is ca 0,21A.

In the pdf ["Extra Manufacturer Data"](https://communityarchive.victronenergy.com/storage/attachments/extra-manufacturer-data-2022-12-14.pdf) IP22 Charger has a record for AC current. It seems as the Victron Reader is decoding this value incorrect. Or have I misunderstood?

![image](https://github.com/user-attachments/assets/33137080-6344-4024-b08b-3a8356c66cb0)

![image](https://github.com/user-attachments/assets/541e12f5-0c68-46ac-bfab-07d226c7acfc)

![image](https://github.com/user-attachments/assets/ab53a8bf-47b5-43b1-905e-40a6a1b1a48c)

**Comment by mp-se** [comment]
The decoding is probably incorrect, i dont have any test data to check against

**Comment by thomasjobs** [comment]
Hmmmmm…….what data do you need?

**Comment by thomasjobs** [comment]
> Preferably a text version of the first image so i dont need to type it in and what the decoded values are in the victron app. Same as before

Ok, I fix.

**Comment by thomasjobs** [comment]
Here the data from the reader.

![Connect and Reader 15dec](https://github.com/user-attachments/assets/a0449a3b-7d2b-42e0-840e-439b41a47a75)
[Data 15dec.txt](https://github.com/user-attachments/files/18140305/Data.15dec.txt)

**Comment by mp-se** [comment]
Thanks, that was the data i needed, will release an update
